#!/bin/bash
CLI_PAGE="docs/content/cli/_index.md"

BACKYCOMMAND="go run backy.go"

{
echo "---
title: CLI
weight: 4
---

This page lists documentation for the CLI.
" 

echo "## Backy "
echo " "
echo "\`\`\`"
eval "${BACKYCOMMAND} -h"
echo "\`\`\`"
echo " "



echo "# Subcommands" 
echo "" 

echo "## backup" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} backup -h"
echo "\`\`\`" 
echo "" 

echo "## cron" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} cron -h"
echo "\`\`\`" 
echo "" 

echo "## exec" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} exec -h"
echo "\`\`\`" 
echo "" 

echo "### exec host" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} exec host -h"
echo "\`\`\`" 
echo "" 


echo "## version" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} version -h"
echo "\`\`\`" 
echo "" 

echo "## list" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} list -h"
echo "\`\`\`" 

echo "## list cmds" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} list cmds -h"
echo "\`\`\`" 

echo "## list lists" 
echo "" 
echo "\`\`\`" 
eval "${BACKYCOMMAND} list lists -h"
echo "\`\`\`" 
} >> _index.md


mv _index.md "$CLI_PAGE"