#!/bin/bash
# export GORELEASER_CURRENT_TAG="$(go run backy.go version -V)"
git tag "$(go run backy.go version -V)"
git push all
git push all --tags
# goreleaser release -f .goreleaser/gitea.yml --clean --release-notes=".changes/$(go run backy.go version -V).md"