#!/bin/bash
export CURRENT_TAG="$(go run backy.go version -V)"
changie batch $CURRENT_TAG
changie merge
git add .changes/
git commit =am "$CURRENT_TAG"
git tag "$CURRENT_TAG"
git push all
git push all --tags
# goreleaser release -f .goreleaser/gitea.yml --clean --release-notes=".changes/$(go run backy.go version -V).md"