steps:
  golang:
    image: golang:1.24
    commands:
      - go install github.com/goreleaser/goreleaser/v2@v2.7.0
      - goreleaser release -f .goreleaser/gitea.yml --release-notes=".changes/$(go run backy.go version -V).md"
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
        
    when:
      event: tag
  # release:
  #   image: goreleaser/goreleaser
  #   commands:

when:
  - event: tag
    branch: master