steps:
  build:
    image: golang
    commands:
      - go build
      - go test
  release:
    image: golangci/golangci-lint:v1.64.7
    commands:
      - golangci-lint run -v --timeout 5m

when:
  - event: push
    branch: develop