pipeline:
  release:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release -f .goreleaser/vern.yml --release-notes=".changes/$(go run backy.go version)"
    secrets: [ gitea_token ]
    when:
      event: tag

branches: master